# Generated by Django 5.2.7 on 2025-10-23 04:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0005_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
