# Generated by Django 5.2.7 on 2025-10-23 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_regularuserproxy_customerproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto Profile')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Nomor WhatsApp')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('address', models.TextField(blank=True, verbose_name='Alamat Lengkap')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Kota')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kode Pos')),
                ('bio', models.TextField(blank=True, verbose_name='Bio/Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Profile Pengguna',
                'verbose_name_plural': 'Profile Pengguna',
            },
        ),
        migrations.DeleteModel(
            name='CustomerProxy',
        ),
    ]
