# Generated by Django 5.2.7 on 2025-10-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_adminuser_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
