# Generated by Django 5.2.7 on 2025-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
    ]
