# Generated by Django 5.2.7 on 2025-10-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_order_shipping_province_shippingaddress_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(max_length=100, verbose_name='Kota/Kabupaten'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Kota/Kabupaten'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kota/Kabupaten'),
        ),
    ]
