# Generated by Django 5.2.7 on 2025-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_shipping_district_shippingaddress_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_city_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='RajaOngkir City ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_courier',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kurir'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_etd',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estimasi Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=100, verbose_name='Layanan Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight',
            field=models.IntegerField(default=0, verbose_name='Total Berat (gram)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=500, help_text='Berat produk dalam gram untuk perhitungan ongkir', verbose_name='Berat (gram)'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='RajaOngkir City ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city_id',
            field=models.IntegerField(blank=True, help_text='ID Kota dari RajaOngkir API', null=True, verbose_name='RajaOngkir City ID'),
        ),
    ]
