# Generated by Django 5.2.7 on 2025-10-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_order_shipping_city_id_order_shipping_courier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_city_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_courier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_etd',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city_id',
        ),
    ]
