# Generated by Django 5.2.7 on 2025-10-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
