# Generated by Django 5.2.7 on 2025-10-29 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6, verbose_name='Kode Verifikasi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Sudah Diverifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Diverifikasi Pada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Verifikasi Email',
                'verbose_name_plural': 'Verifikasi Email',
            },
        ),
    ]
