# Generated by Django 5.2.7 on 2025-11-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='midtrans_order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID Midtrans'),
        ),
        migrations.AddField(
            model_name='order',
            name='midtrans_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Transaksi Midtrans'),
        ),
    ]
