# Generated by Django 5.2.7 on 2025-11-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_order_midtrans_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='midtrans_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='midtrans_transaction_id',
        ),
    ]
