# Generated by Django 5.2.7 on 2025-11-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_order_midtrans_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='midtrans_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Midtrans Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='midtrans_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipe Pembayaran Midtrans'),
        ),
        migrations.AddField(
            model_name='order',
            name='midtrans_snap_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Snap Token'),
        ),
        migrations.AddField(
            model_name='order',
            name='midtrans_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Midtrans Transaction ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='midtrans_transaction_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Transaksi Midtrans'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('midtrans', 'Midtrans Payment Gateway'), ('bank_transfer', 'Transfer Bank'), ('qris', 'QRIS'), ('cod', 'Cash on Delivery')], max_length=20, verbose_name='Metode Pembayaran'),
        ),
    ]
