# Generated by Django 5.2.7 on 2025-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_order_midtrans_order_id_order_midtrans_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Makassar', max_length=100, verbose_name='Kota')),
                ('district', models.CharField(max_length=100, unique=True, verbose_name='Kecamatan')),
                ('rate', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tarif Ongkir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Tarif Ongkir',
                'verbose_name_plural': 'Tarif Ongkir',
                'ordering': ['city', 'district'],
            },
        ),
    ]
