# Generated by Django 5.2.7 on 2025-11-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_shippingrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRate',
        ),
    ]
