# Generated by Django 5.2.7 on 2025-11-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_delete_shippingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=100, unique=True, verbose_name='Kecamatan')),
                ('harga', models.DecimalField(decimal_places=0, default=10000, max_digits=10, verbose_name='Harga Ongkir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Biaya Pengiriman',
                'verbose_name_plural': 'Biaya Pengiriman',
                'ordering': ['kecamatan'],
            },
        ),
    ]
