# Generated by Django 5.2.7 on 2025-11-11 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_shippingcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Voucher')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10, verbose_name='Tipe Diskon')),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nilai Diskon')),
                ('min_purchase_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Belanja')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maksimal Diskon')),
                ('valid_from', models.DateTimeField(verbose_name='Berlaku Dari')),
                ('valid_to', models.DateTimeField(verbose_name='Berlaku Sampai')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Batas Penggunaan')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Digunakan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Voucher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Voucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Diskon Voucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.voucher', verbose_name='Voucher'),
        ),
    ]
