# Generated by Django 5.2.7 on 2025-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_voucher_order_voucher_code_order_voucher_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('express', 'Express')], default='reguler', max_length=10, verbose_name='Tipe Pengiriman'),
        ),
    ]
