# Generated by Django 5.2.7 on 2025-11-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_order_shipping_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_type',
        ),
    ]
