# Generated by Django 5.2.7 on 2025-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('reguler', 'Reguler'), ('express', 'Express')], default='reguler', max_length=20),
        ),
    ]
