# Generated by Django 5.2.7 on 2025-11-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('delivery', 'Delivery (Dikirim)'), ('pickup', 'Pick Up (Ambil Sendiri)')], default='delivery', max_length=20, verbose_name='Metode Pengiriman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Sudah Dibayar'), ('processing', 'Sedang Diproses'), ('shipped', 'Dikirim'), ('delivered', 'Terkirim'), ('cancelled', 'Dibatalkan'), ('ready_for_pickup', 'Siap Diambil')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
