# Generated by Django 5.2.7 on 2025-11-12 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_order_shipping_method_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6, verbose_name='Kode Verifikasi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Sudah Diverifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Diverifikasi Pada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Verifikasi Perubahan Password',
                'verbose_name_plural': 'Verifikasi Perubahan Password',
                'ordering': ['-created_at'],
            },
        ),
    ]
