# Generated by Django 5.2.7 on 2025-11-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_passwordchangeverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChangeVerification',
        ),
    ]
